# Country List from https://github.com/bernawastaken/country-list
# FIle under the MIT License

CREATE TABLE IF NOT EXISTS Country_List (
    `countryID` INT,
    `countryName` VARCHAR(32) CHARACTER SET utf8,
    `countryISO` VARCHAR(2) CHARACTER SET utf8,
    `countryISO3` VARCHAR(3) CHARACTER SET utf8
);
INSERT INTO Country_List VALUES
    (1,'Afghanistan','AF','AFG'),
    (2,'Albania','AL','ALB'),
    (3,'Algeria','DZ','DZA'),
    (4,'American Samoa','AS','ASM'),
    (5,'Andorra','AD','AND'),
    (6,'Angola','AO','AGO'),
    (7,'Anguilla','AI','AIA'),
    (8,'Antarctica','AQ','ATA'),
    (9,'Antigua and Barbuda','AG','ATG'),
    (10,'Argentina','AR','ARG'),
    (11,'Armenia','AM','ARM'),
    (12,'Aruba','AW','ABW'),
    (13,'Australia','AU','AUS'),
    (14,'Austria','AT','AUT'),
    (15,'Azerbaijan','AZ','AZE'),
    (16,'Bahamas','BS','BHS'),
    (17,'Bahrain','BH','BHR'),
    (18,'Bangladesh','BD','BGD'),
    (19,'Barbados','BB','BRB'),
    (20,'Belarus','BY','BLR'),
    (21,'Belgium','BE','BEL'),
    (22,'Belize','BZ','BLZ'),
    (23,'Benin','BJ','BEN'),
    (24,'Bermuda','BM','BMU'),
    (25,'Bhutan','BT','BTN'),
    (26,'Bolivia','BO','BOL'),
    (27,'Bosnia and Herzegovina','BA','BIH'),
    (28,'Botswana','BW','BWA'),
    (29,'Brazil','BR','BRA'),
    (30,'British Indian Ocean Territory','IO','IOT'),
    (31,'British Virgin Islands','VG','VGB'),
    (32,'Brunei','BN','BRN'),
    (33,'Bulgaria','BG','BGR'),
    (34,'Burkina Faso','BF','BFA'),
    (35,'Burundi','BI','BDI'),
    (36,'Cambodia','KH','KHM'),
    (37,'Cameroon','CM','CMR'),
    (38,'Canada','CA','CAN'),
    (39,'Cape Verde','CV','CPV'),
    (40,'Cayman Islands','KY','CYM'),
    (41,'Central African Republic','CF','CAF'),
    (42,'Chad','TD','TCD'),
    (43,'Chile','CL','CHL'),
    (44,'China','CN','CHN'),
    (45,'Christmas Island','CX','CXR'),
    (46,'Cocos Islands','CC','CCK'),
    (47,'Colombia','CO','COL'),
    (48,'Comoros','KM','COM'),
    (49,'Cook Islands','CK','COK'),
    (50,'Costa Rica','CR','CRI'),
    (51,'Croatia','HR','HRV'),
    (52,'Cuba','CU','CUB'),
    (53,'Curacao','CW','CUW'),
    (54,'Cyprus','CY','CYP'),
    (55,'Czech Republic','CZ','CZE'),
    (56,'Democratic Republic of the Congo','CD','COD'),
    (57,'Denmark','DK','DNK'),
    (58,'Djibouti','DJ','DJI'),
    (59,'Dominica','DM','DMA'),
    (60,'Dominican Republic','DO','DOM'),
    (61,'East Timor','TL','TLS'),
    (62,'Ecuador','EC','ECU'),
    (63,'Egypt','EG','EGY'),
    (64,'El Salvador','SV','SLV'),
    (65,'Equatorial Guinea','GQ','GNQ'),
    (66,'Eritrea','ER','ERI'),
    (67,'Estonia','EE','EST'),
    (68,'Ethiopia','ET','ETH'),
    (69,'Falkland Islands','FK','FLK'),
    (70,'Faroe Islands','FO','FRO'),
    (71,'Fiji','FJ','FJI'),
    (72,'Finland','FI','FIN'),
    (73,'France','FR','FRA'),
    (74,'French Polynesia','PF','PYF'),
    (75,'Gabon','GA','GAB'),
    (76,'Gambia','GM','GMB'),
    (77,'Georgia','GE','GEO'),
    (78,'Germany','DE','DEU'),
    (79,'Ghana','GH','GHA'),
    (80,'Gibraltar','GI','GIB'),
    (81,'Greece','GR','GRC'),
    (82,'Greenland','GL','GRL'),
    (83,'Grenada','GD','GRD'),
    (84,'Guam','GU','GUM'),
    (85,'Guatemala','GT','GTM'),
    (86,'Guernsey','GG','GGY'),
    (87,'Guinea','GN','GIN'),
    (88,'Guinea-Bissau','GW','GNB'),
    (89,'Guyana','GY','GUY'),
    (90,'Haiti','HT','HTI'),
    (91,'Honduras','HN','HND'),
    (92,'Hong Kong','HK','HKG'),
    (93,'Hungary','HU','HUN'),
    (94,'Iceland','IS','ISL'),
    (95,'India','IN','IND'),
    (96,'Indonesia','ID','IDN'),
    (97,'Iran','IR','IRN'),
    (98,'Iraq','IQ','IRQ'),
    (99,'Ireland','IE','IRL'),
    (100,'Isle of Man','IM','IMN'),
    (101,'Israel','IL','ISR'),
    (102,'Italy','IT','ITA'),
    (103,'Ivory Coast','CI','CIV'),
    (104,'Jamaica','JM','JAM'),
    (105,'Japan','JP','JPN'),
    (106,'Jersey','JE','JEY'),
    (107,'Jordan','JO','JOR'),
    (108,'Kazakhstan','KZ','KAZ'),
    (109,'Kenya','KE','KEN'),
    (110,'Kiribati','KI','KIR'),
    (111,'Kosovo','XK','XKX'),
    (112,'Kuwait','KW','KWT'),
    (113,'Kyrgyzstan','KG','KGZ'),
    (114,'Laos','LA','LAO'),
    (115,'Latvia','LV','LVA'),
    (116,'Lebanon','LB','LBN'),
    (117,'Lesotho','LS','LSO'),
    (118,'Liberia','LR','LBR'),
    (119,'Libya','LY','LBY'),
    (120,'Liechtenstein','LI','LIE'),
    (121,'Lithuania','LT','LTU'),
    (122,'Luxembourg','LU','LUX'),
    (123,'Macau','MO','MAC'),
    (124,'Macedonia','MK','MKD'),
    (125,'Madagascar','MG','MDG'),
    (126,'Malawi','MW','MWI'),
    (127,'Malaysia','MY','MYS'),
    (128,'Maldives','MV','MDV'),
    (129,'Mali','ML','MLI'),
    (130,'Malta','MT','MLT'),
    (131,'Marshall Islands','MH','MHL'),
    (132,'Mauritania','MR','MRT'),
    (133,'Mauritius','MU','MUS'),
    (134,'Mayotte','YT','MYT'),
    (135,'Mexico','MX','MEX'),
    (136,'Micronesia','FM','FSM'),
    (137,'Moldova','MD','MDA'),
    (138,'Monaco','MC','MCO'),
    (139,'Mongolia','MN','MNG'),
    (140,'Montenegro','ME','MNE'),
    (141,'Montserrat','MS','MSR'),
    (142,'Morocco','MA','MAR'),
    (143,'Mozambique','MZ','MOZ'),
    (144,'Myanmar','MM','MMR'),
    (145,'Namibia','NA','NAM'),
    (146,'Nauru','NR','NRU'),
    (147,'Nepal','NP','NPL'),
    (148,'Netherlands','NL','NLD'),
    (149,'Netherlands Antilles','AN','ANT'),
    (150,'New Caledonia','NC','NCL'),
    (151,'New Zealand','NZ','NZL'),
    (152,'Nicaragua','NI','NIC'),
    (153,'Niger','NE','NER'),
    (154,'Nigeria','NG','NGA'),
    (155,'Niue','NU','NIU'),
    (156,'North Korea','KP','PRK'),
    (157,'Northern Mariana Islands','MP','MNP'),
    (158,'Norway','NO','NOR'),
    (159,'Oman','OM','OMN'),
    (160,'Pakistan','PK','PAK'),
    (161,'Palau','PW','PLW'),
    (162,'Palestine','PS','PSE'),
    (163,'Panama','PA','PAN'),
    (164,'Papua New Guinea','PG','PNG'),
    (165,'Paraguay','PY','PRY'),
    (166,'Peru','PE','PER'),
    (167,'Philippines','PH','PHL'),
    (168,'Pitcairn','PN','PCN'),
    (169,'Poland','PL','POL'),
    (170,'Portugal','PT','PRT'),
    (171,'Puerto Rico','PR','PRI'),
    (172,'Qatar','QA','QAT'),
    (173,'Republic of the Congo','CG','COG'),
    (174,'Reunion','RE','REU'),
    (175,'Romania','RO','ROU'),
    (176,'Russia','RU','RUS'),
    (177,'Rwanda','RW','RWA'),
    (178,'Saint Barthelemy','BL','BLM'),
    (179,'Saint Helena','SH','SHN'),
    (180,'Saint Kitts and Nevis','KN','KNA'),
    (181,'Saint Lucia','LC','LCA'),
    (182,'Saint Martin','MF','MAF'),
    (183,'Saint Pierre and Miquelon','PM','SPM'),
    (184,'Saint Vincent and the Grenadines','VC','VCT'),
    (185,'Samoa','WS','WSM'),
    (186,'San Marino','SM','SMR'),
    (187,'Sao Tome and Principe','ST','STP'),
    (188,'Saudi Arabia','SA','SAU'),
    (189,'Senegal','SN','SEN'),
    (190,'Serbia','RS','SRB'),
    (191,'Seychelles','SC','SYC'),
    (192,'Sierra Leone','SL','SLE'),
    (193,'Singapore','SG','SGP'),
    (194,'Sint Maarten','SX','SXM'),
    (195,'Slovakia','SK','SVK'),
    (196,'Slovenia','SI','SVN'),
    (197,'Solomon Islands','SB','SLB'),
    (198,'Somalia','SO','SOM'),
    (199,'South Africa','ZA','ZAF'),
    (200,'South Korea','KR','KOR'),
    (201,'South Sudan','SS','SSD'),
    (202,'Spain','ES','ESP'),
    (203,'Sri Lanka','LK','LKA'),
    (204,'Sudan','SD','SDN'),
    (205,'Suriname','SR','SUR'),
    (206,'Svalbard and Jan Mayen','SJ','SJM'),
    (207,'Swaziland','SZ','SWZ'),
    (208,'Sweden','SE','SWE'),
    (209,'Switzerland','CH','CHE'),
    (210,'Syria','SY','SYR'),
    (211,'Taiwan','TW','TWN'),
    (212,'Tajikistan','TJ','TJK'),
    (213,'Tanzania','TZ','TZA'),
    (214,'Thailand','TH','THA'),
    (215,'Togo','TG','TGO'),
    (216,'Tokelau','TK','TKL'),
    (217,'Tonga','TO','TON'),
    (218,'Trinidad and Tobago','TT','TTO'),
    (219,'Tunisia','TN','TUN'),
    (220,'Turkey','TR','TUR'),
    (221,'Turkmenistan','TM','TKM'),
    (222,'Turks and Caicos Islands','TC','TCA'),
    (223,'Tuvalu','TV','TUV'),
    (224,'U.S. Virgin Islands','VI','VIR'),
    (225,'Uganda','UG','UGA'),
    (226,'Ukraine','UA','UKR'),
    (227,'United Arab Emirates','AE','ARE'),
    (228,'United Kingdom','GB','GBR'),
    (229,'United States','US','USA'),
    (230,'Uruguay','UY','URY'),
    (231,'Uzbekistan','UZ','UZB'),
    (232,'Vanuatu','VU','VUT'),
    (233,'Vatican','VA','VAT'),
    (234,'Venezuela','VE','VEN'),
    (235,'Vietnam','VN','VNM'),
    (236,'Wallis and Futuna','WF','WLF'),
    (237,'Western Sahara','EH','ESH'),
    (238,'Yemen','YE','YEM'),
    (239,'Zambia','ZM','ZMB'),
    (240,'Zimbabwe','ZW','ZWE');
